Repository MaeumGaGym/MaeumGaGym_iOS, pull requests merged in 2023-11, with the labels that each got.

#10 9 라이브러리 추가
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Modules/ThirdPartyLibs/Project.swift
  Tuist/Dependencies.swift
Labels: 기능 추가

#11 9 라이브러리 추가
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Modules/ThirdPartyLibs/Project.swift
  Tuist/Dependencies.swift
Labels: 기능 추가

#18 리펙토링 다함
  Projects/Modules/DSKit/Demo/Sources/Application/DesignSystemViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/Button/Auth/ButtonViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/Button/Certification/CertificationButtonViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/CertificationButton/CertificationButton.swift
Labels: 리펙토링

#19 ⚓️ :: [#17] pickle feature 추가
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  Projects/Features/PickleFeature/Demo/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/Features/PickleFeature/Demo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/Features/PickleFeature/Demo/Resources/Assets.xcassets/Contents.json
  Projects/Features/PickleFeature/Demo/Resources/Launch Screen.storyboard
  Projects/Features/PickleFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/PickleFeature/Demo/Sources/SceneDelegate.swift
  Projects/Features/PickleFeature/Interface/Sources/dummy1.swift
  Projects/Features/PickleFeature/Project.swift
  Projects/Features/PickleFeature/Sources/SignInScene/VC/LoginViewController.swift
  Projects/Features/PickleFeature/Sources/SignInScene/ViewModel/LoginViewModel.swift
  Projects/Features/PickleFeature/Tests/Resources/dummy.txt
  Projects/Features/PickleFeature/Tests/Sources/UnitTest.swift
Labels: 기능 추가

#22 Auth 버튼 리펙토링
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/Button/Auth/ButtonViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DesignSystemDemo/DesignSystemViewController.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/Logo/AppleLogo.imageset/AppleLogo.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Logo/AppleLogo.imageset/AppleLogo@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Logo/AppleLogo.imageset/AppleLogo@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Logo/GoogleLogo.imageset/GoogleLogo.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Logo/GoogleLogo.imageset/GoogleLogo@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Logo/GoogleLogo.imageset/GoogleLogo@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Logo/kakaoLogo.imageset/kakaoLogo.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Logo/kakaoLogo.imageset/kakaoLogo@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Logo/kakaoLogo.imageset/kakaoLogo@3x.png
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Auth/AuthLogoType.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Certification/MaeumGaGym+CertificationButton.swift
Labels: 리펙토링

#29 startPage 완성
  Projects/Core/Sources/Setp/AppStep.swift
  Projects/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/AuthFeature/Demo/Sources/SceneDelegate.swift
  Projects/Features/AuthFeature/Interface/Sources/AppStepper.swift
  Projects/Features/AuthFeature/Interface/Sources/dummy1.swift
  Projects/Features/AuthFeature/Interface/Sources/sdaf.swift
  Projects/Features/AuthFeature/Sources/SignInScene/VC/LoginViewController.swift
  Projects/Features/AuthFeature/Sources/SignInScene/ViewModel/LoginViewModel.swift
  Projects/Features/AuthFeature/Sources/StartScene/VC/StartViewController.swift
  Projects/Features/AuthFeature/Sources/StartScene/ViewModel/StartViewModel.swift
  Projects/Features/PickleFeature/Project.swift
  Projects/Features/RootFeature/Sources/AppFlow.swift
  Projects/Features/RootFeature/Sources/StartFlow.swift
Labels: 기능 추가

#31 일단 SceneDelegate 사용
  Projects/Features/AuthFeature/Demo/Sources/SceneDelegate.swift
  Projects/Features/AuthFeature/Interface/Sources/AppStepper.swift
  Projects/Features/AuthFeature/Interface/Sources/AuthFlow.swift
  Projects/Features/AuthFeature/Interface/Sources/sdaf.swift
  Projects/Features/RootFeature/Sources/AppFlow.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 기능 추가

#39 예제 코드 수정
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/Button/ButtonViewController.swift
Labels: 버그 고치기

#45 탭바 리펙
  Projects/Core/Sources/Setp/AppStep.swift
  Projects/Features/RootFeature/Sources/AppFlow.swift
  Projects/Features/RootFeature/Sources/HomeFlow.swift
  Projects/Features/RootFeature/Sources/PickleFlow.swift
  Projects/Features/RootFeature/Sources/PostureFlow.swift
  Projects/Features/RootFeature/Sources/SelfCareFlow.swift
  Projects/Features/RootFeature/Sources/ShopFlow.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/BlackHome.imageset/BlackHome.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/BlackHome.imageset/BlackHome@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/BlackHome.imageset/BlackHome@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/BlackHome.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/BlackPickle.imageset/BlackPickle.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/BlackPickle.imageset/BlackPickle@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/BlackPickle.imageset/BlackPickle@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/BlackPickle.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/MaeumGaGymBlackPeople.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/MaeumGaGymBlackPeople.imageset/MaeumGaGymPeople.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/MaeumGaGymBlackPeople.imageset/MaeumGaGymPeople@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/MaeumGaGymBlackPeople.imageset/MaeumGaGymPeople@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/WhiteHome.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/WhiteHome.imageset/WhiteHome.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/WhiteHome.imageset/WhiteHome@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/WhiteHome.imageset/WhiteHome@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/WhiteMuscle.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/WhiteMuscle.imageset/muscle.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/WhiteMuscle.imageset/muscle@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/WhiteMuscle.imageset/muscle@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/WhitePickle.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/WhitePickle.imageset/WhitePickle.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/WhitePickle.imageset/WhitePickle@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/WhitePickle.imageset/WhitePickle@3x.png
Labels: 리펙토링
