Repository MaeumGaGym/MaeumGaGym_iOS, pull requests merged in 2024-04, with the labels that each got.

#293 :: [IOS-61] selfCareMyRoutine
  Projects/Features/SelfCareFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/View/SelfCareMyRoutineDetailViewController.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/View/SelfCareMyRoutineEditViewController.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/View/SelfCareMyRoutineViewController.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/View/SelfCareRoutineNavigationBar.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/View/SelfCareViewController.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/ViewModel/SelfCareMyRoutine+VM.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/ViewModel/SelfCareMyRoutineDetail+VM.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/ViewModel/SelfCareMyRoutineEdit+VM.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Detail/MyRoutineDetailTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineEditTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Main/MyRoutineTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButton.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButtonType.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymLabel /MG+Label.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/SelfCareResourcesService.swift
Labels: kind/리펙토링, kind/기능

#294 :: [IOS-63] 자기관리 - 내 루틴 - 디테일
  Projects/Features/SelfCareFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/View/SelfCareMyRoutineDetailViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/Target/SelfCareTargetMainViewController.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Detail/MyRoutineDetailTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButtonType.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/Target/Main/TargetMainTableViewCell.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/Alert/DSCaveatAlertViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/Button/DSAgreeButtonVC.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/UILabel/DSPostureInfoLabelVC.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/UILabel/DSTagLabelVC.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/blackEarth.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/blackEarth.imageset/blackEarth.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/blackEarth.imageset/blackEarth@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/blackEarth.imageset/blackEarth@3x.png
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/CaveatAlert/MGIconTextAlertViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/CaveatAlert/MGViewController.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/SelfCareResourcesService.swift
Labels: kind/리펙토링, kind/기능

#295 :: [IOS-64] 자기관리 - 루틴 수정 페이지
  Projects/Core/Sources/Base/BaseView.swift
  Projects/Domain/Sources/Model/SelfCare/SelfCareMyRoutineEditModel.swift
  Projects/Features/SelfCareFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/View/SelfCareMyRoutineEditViewController.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/View/SelfCareRoutineNavigationBar.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineCountView.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineDateCollectionViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineDateTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineEditTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButton.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButtonType.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymVIew/MG+SearchView.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/SelfCareResourcesService.swift
  Projects/Modules/MGNetworks/Sources/Service/SelfCareService.swift
Labels: kind/리펙토링, kind/기능

#296 :: [IOS-77] poseAPI 구축
  Projects/Modules/MGNetworks/Sources/API/Pose/PostureAPI.swift
  Projects/Modules/MGNetworks/Sources/Foundation/Base/APIType.swift
  Projects/Modules/MGNetworks/Sources/Foundation/Base/BaseAPI.swift
Labels: kind/기능

#297 탭바 에러 수정
  Projects/Core/Sources/Coordinator/Setp/AppStep.swift
  Projects/Core/Sources/Coordinator/Stepper/PickleStepper.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAHomeTapBar.imageset/BlackHome.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAHomeTapBar.imageset/BlackHome@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAHomeTapBar.imageset/BlackHome@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAHomeTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAMuscleTapBar.imageset/BlackMuscle.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAMuscleTapBar.imageset/BlackMuscle@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAMuscleTapBar.imageset/BlackMuscle@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAMuscleTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAPickleTapBar.imageset/BlackPickle.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAPickleTapBar.imageset/BlackPickle@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAPickleTapBar.imageset/BlackPickle@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAPickleTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAShopTapBar.imageset/BlackShop.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAShopTapBar.imageset/BlackShop@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAShopTapBar.imageset/BlackShop@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BAShopTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BPeopleTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BPeopleTapBar.imageset/MaeumGaGymBlackPeople.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BPeopleTapBar.imageset/MaeumGaGymBlackPeople@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BPeopleTapBar.imageset/MaeumGaGymBlackPeople@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlHomeTapBar.imageset/BlueHome.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlHomeTapBar.imageset/BlueHome@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlHomeTapBar.imageset/BlueHome@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlHomeTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlMuscleTapBar.imageset/BlueMuscle.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlMuscleTapBar.imageset/BlueMuscle@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlMuscleTapBar.imageset/BlueMuscle@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlMuscleTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlPeopleTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlPeopleTapBar.imageset/MaeumGaGymBluePeople.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlPeopleTapBar.imageset/MaeumGaGymBluePeople@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlPeopleTapBar.imageset/MaeumGaGymBluePeople@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlPickleTapBar.imageset/BluePickle.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlPickleTapBar.imageset/BluePickle@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlPickleTapBar.imageset/BluePickle@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlPickleTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlShopTapBar.imageset/BlueShop.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlShopTapBar.imageset/BlueShop@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlShopTapBar.imageset/BlueShop@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/BlShopTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/WhitePickle.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/WhitePickle.imageset/WhitePickle.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/WhitePickle.imageset/WhitePickle@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Tabars/WhitePickle.imageset/WhitePickle@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/TapBar/Contents.json
  Projects/Modules/DSKit/Sources/Components/MGTabBarType/MGTabBarType.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymProfile/MG+ProfileView.swift
  Projects/Modules/MGFlow/Sources/Flow/HomeFlow.swift
  Projects/Modules/MGFlow/Sources/Flow/InitFlow.swift
  Projects/Modules/MGFlow/Sources/Flow/MainTabBarContoller.swift
  Projects/Modules/MGFlow/Sources/Flow/PickleFlow.swift
  Projects/Modules/MGFlow/Sources/Flow/PostureFlow.swift
  Projects/Modules/MGFlow/Sources/Flow/SelfCareFlow.swift
  Projects/Modules/MGFlow/Sources/Flow/ShopFlow.swift
Labels: kind/버그, approved

#298 :: dummy Data 추가
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Extra/ExtraCollectionViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Routine/RoutineCollectionCell.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAHomeTapBar.imageset/BlackHome.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAHomeTapBar.imageset/BlackHome@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAHomeTapBar.imageset/BlackHome@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAHomeTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAMuscleTapBar.imageset/BlackMuscle.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAMuscleTapBar.imageset/BlackMuscle@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAMuscleTapBar.imageset/BlackMuscle@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAMuscleTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAPickleTapBar.imageset/BlackPickle.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAPickleTapBar.imageset/BlackPickle@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAPickleTapBar.imageset/BlackPickle@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAPickleTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAShopTapBar.imageset/BlackShop.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAShopTapBar.imageset/BlackShop@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAShopTapBar.imageset/BlackShop@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BAShopTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BPeopleTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BPeopleTapBar.imageset/MaeumGaGymBlackPeople.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BPeopleTapBar.imageset/MaeumGaGymBlackPeople@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BPeopleTapBar.imageset/MaeumGaGymBlackPeople@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlHomeTapBar.imageset/BlueHome.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlHomeTapBar.imageset/BlueHome@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlHomeTapBar.imageset/BlueHome@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlHomeTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlMuscleTapBar.imageset/BlueMuscle.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlMuscleTapBar.imageset/BlueMuscle@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlMuscleTapBar.imageset/BlueMuscle@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlMuscleTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlPeopleTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlPeopleTapBar.imageset/MaeumGaGymBluePeople.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlPeopleTapBar.imageset/MaeumGaGymBluePeople@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlPeopleTapBar.imageset/MaeumGaGymBluePeople@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlPickleTapBar.imageset/BluePickle.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlPickleTapBar.imageset/BluePickle@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlPickleTapBar.imageset/BluePickle@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlPickleTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlShopTapBar.imageset/BlueShop.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlShopTapBar.imageset/BlueShop@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlShopTapBar.imageset/BlueShop@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/BlShopTapBar.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/WhitePickle.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/WhitePickle.imageset/WhitePickle.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/WhitePickle.imageset/WhitePickle@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Tabars/WhitePickle.imageset/WhitePickle@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/calculatorIcon.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/calculatorIcon.imageset/calculatorIcon.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/timerIcon.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/timerIcon.imageset/timerIcon.png
  Projects/Modules/MGNetworks/Sources/Service/HomeService.swift
Labels: kind/기능, size/M, approved

#302 DOC:: [#301] 리드미 수정
  README.md
Labels: kind/문서, size/XS, approved

#303 REFAC :: auth 수정중
  Projects/Core/Sources/Coordinator/Setp/AppStep.swift
  Projects/Core/Sources/Coordinator/Stepper/AuthStepper.swift
  Projects/Data/Sources/Repository/AuthRepository.swift
  Projects/Domain/Sources/RepositoryInterface/AuthRepositoryInterface.swift
  Projects/Domain/Sources/Response/LoginDTO.swift
  Projects/Domain/Sources/UseCase/AuthUseCase.swift
  Projects/Features/AuthFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/AuthFeature/Sources/IntroScene/VC/SplashViewController.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/SplashViewModel.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/MGSplashIcon.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/MGSplashIcon.imageset/MGSplashIcon.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/MGSplashIcon.imageset/MGSplashIcon@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/MGSplashIcon.imageset/MGSplashIcon@3x.png
  Projects/Modules/MGFlow/Sources/Flow/AuthFlow.swift
  Projects/Modules/MGNetworks/Sources/API/Auth/AppleAPI.swift
  Projects/Modules/MGNetworks/Sources/API/Auth/AuthAPI.swift
  Projects/Modules/MGNetworks/Sources/API/Auth/GoogleAPI.swift
  Projects/Modules/MGNetworks/Sources/API/Auth/KakaoAPI.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/AuthResourcesService.swift
  Projects/Modules/MGNetworks/Sources/Service/AuthService.swift
  Projects/Modules/TokenManager/Sources/KeychainType.swift
Labels: kind/리펙토링, approved, size/XL

#306 :: 작업 중지
  Projects/Data/Sources/Repository/AuthRepository.swift
  Projects/Domain/Sources/UseCase/AuthUseCase.swift
  Projects/Features/AuthFeature/Sources/IntroScene/VC/IntroViewController.swift
  Projects/Features/AuthFeature/Sources/IntroScene/VC/SplashViewController.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/IntroViewModel.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/SplashViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/AgreeViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/AuthNavigationBarBar.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/NicknameViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/AgreeViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/NicknameViewModel.swift
  Projects/Features/PickleFeature/Sources/PickleScene/VC/PickleCell.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Detail/PostureDetailViewController.swift
  Projects/Modules/MGNetworks/Sources/Service/AuthService.swift
  Supporting/AuthResourcesService.swift
  Supporting/ResourcesService/PickleResourcesService.swift
Labels: kind/리펙토링, size/L, approved
