Repository MaeumGaGym/MaeumGaGym_iOS, pull requests merged in 2024-02, with the labels that each got.

#156 🔀 :: [#155] 자기관리 - 내 루틴 - 루틴 수정
  Projects/Features/SelfCareFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareMyRoutineDetailViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareMyRoutineEditViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareMyRoutineViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/ViewModel/SelfCareMyRoutineEdit+VM.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineCountView.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineCountViewType.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineEditModel.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineEditTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButton.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButtonType.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCarePlus.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCarePlus.imageset/SelfCarePlus.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCarePlus.imageset/SelfCarePlus@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCarePlus.imageset/SelfCarePlus@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/selfCareDelete.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/selfCareDelete.imageset/selfCareDelete.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/selfCareDelete.imageset/selfCareDelete@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/selfCareDelete.imageset/selfCareDelete@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/selfCareMinus.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/selfCareMinus.imageset/selfCareMinus.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/selfCareMinus.imageset/selfCareMinus@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/selfCareMinus.imageset/selfCareMinus@3x.png
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymTextField/MG+TitleTextField.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymTextField/TitleTextFieldType.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymVIew/MG+TitleTextView.swift
Labels: 기능 추가

#162 💉:: [#161] goolge Oauth 기반 info 설정
  Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlists.swift
  Projects/Features/AuthFeature/Demo/Sources/AppDelegate.swift
  Tuist/Dependencies.swift
Labels: 고치지 않음

#165 164 카카오톡 OAuth 추가
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlists.swift
  Projects/Data/Sources/Repository/AuthRepository.swift
  Projects/Domain/Sources/Error/Auth/AuthError.swift
  Projects/Domain/Sources/Model/Auth/User.swift
  Projects/Domain/Sources/RepositoryInterface/AuthRepositoryInterface.swift
  Projects/Domain/Sources/UseCase/AuthUseCase.swift
  Projects/Features/AuthFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/AuthFeature/Demo/Sources/SceneDelegate.swift
  Projects/Features/AuthFeature/Interface/Sources/AuthFlow.swift
  Projects/Features/AuthFeature/Interface/Sources/AuthPresentable.swift
  Projects/Features/AuthFeature/Sources/IntroScene/VC/IntroViewController.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/IntroViewModel.swift
  Projects/Features/AuthFeature/Sources/Test/KakaoOauthTestViewController.swift
  Projects/Modules/MGNetworks/Sources/Service/AuthService.swift
  Projects/Modules/ThirdPartyLibs/Project.swift
  Tuist/Dependencies.swift
Labels: 리펙토링, 기능 추가

#167 ⚓️ :: [#158] 타이머 View 중간 점검
  Projects/Features/HomeFeature/Demo/Sources/SceneDelegate.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/HomeTimerView.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/MinGymKit/MinGaGymTimerKit.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/MinGymKit/MinGymKit.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerAlarmAlertView.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerCollectionViewCell.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerHeaderCollectionViewCell.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerModel.swift
  Projects/Features/HomeFeature/Sources/TimerScene/View/TimerViewController.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/Home/homeTimerBell.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Home/homeTimerBell.imageset/homeTimerBell.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Home/homeTimerBell.imageset/homeTimerBell@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Home/homeTimerBell.imageset/homeTimerBell@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Home/homeTimerLogo.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Home/homeTimerLogo.imageset/homeTimerLogo.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Home/homeTimerLogo.imageset/homeTimerLogo@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Home/homeTimerLogo.imageset/homeTimerLogo@3x.png
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymVIew/MG+ProgressBarView.swift
  Projects/Modules/DSKit/Sources/Components/Shadow.swift
  Projects/Modules/DSKit/Sources/UIFont+.swift
Labels: 기능 추가

#173 전체적인 코드 리펙토링
  Projects/Core/Sources/Base/BaseButton.swift
  Projects/Core/Sources/Base/BaseLabel.swift
  Projects/Core/Sources/Base/BaseViewController.swift
  Projects/Core/Sources/Base/BaseViewModel.swift
  Projects/Core/Sources/Utils/Double+Utils.swift
  Projects/Core/Sources/Utils/UIView+Utils.swift
  Projects/Domain/Sources/Model/Auth/User.swift
  Projects/Domain/Sources/UseCase/HomeUseCase.swift
  Projects/Features/AuthFeature/Sources/IntroScene/VC/IntroViewController.swift
  Projects/Features/BaseFeatureDependency/Sources/Foundation/BaseCoordinator.swift
  Projects/Features/BaseFeatureDependency/Sources/Foundation/Coordinator.swift
  Projects/Features/BaseFeatureDependency/Sources/Foundation/CoordinatorFinishiOutput.swift
  Projects/Features/BaseFeatureDependency/Sources/Options/CoordinatorStartingOption.swift
  Projects/Features/BaseFeatureDependency/Sources/Options/DeepLinkOptions.swift
  Projects/Features/BaseFeatureDependency/Sources/Options/LaunchInstructors.swift
  Projects/Features/BaseFeatureDependency/Sources/Router/Router.swift
  Projects/Features/HomeFeature/Interface/Sources/HomePresentable.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/StepNumber/StepTableViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/View/NavigationBar/HomeNavigationBar.swift
Labels: 리펙토링

#175 174 메트로눔 개발
  Projects/Domain/Project.swift
  Projects/Features/HomeFeature/Demo/Resources/High.wav
  Projects/Features/HomeFeature/Demo/Resources/Low.wav
  Projects/Features/HomeFeature/Demo/Sources/SceneDelegate.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Extra/ExtraTableViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Routine/RoutineTableViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/StepNumber/StepTableViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/View/NavigationBar/HomeNavigationBar.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/Metronome.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/MetronomeType.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/MetronomeViewController.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/MetronomeViewModel.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/HomeTimerView.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/MinGymKit/MinGaGymTimerKit.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/MinGymKit/MinGymKit.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/MinGymKit/Stopwatch.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerAlarmAlertView.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerCollectionViewCell.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerEditView.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerHeaderCollectionViewCell.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerModel.swift
  Projects/Features/HomeFeature/Sources/TimerScene/View/TimerViewController.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/BPM/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/BPM/vibration.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/BPM/vibration.imageset/vibration.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/BPM/vibration.imageset/vibration@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/BPM/vibration.imageset/vibration@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/BPM/volume.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/BPM/volume.imageset/volume.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/BPM/volume.imageset/volume@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/BPM/volume.imageset/volume@3x.png
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Timer/TimerButtonType.swift
Labels: 기능 추가

#177 BPM 로직 구현
  Projects/Features/HomeFeature/Sources/MetronomeScene/Metronome.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/MetronomeType.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/MetronomeViewController.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/MetronomeViewModel.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/View/NavigationBar/MetronomeNavigationBar.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/HorizontalPicker/DSHorizontalPickerViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/Slider/DSSliderViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DesignSystemDemo/ComponentsDemoTableViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymHorizontalPicker/HorizontalPickerViewDelegate.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymHorizontalPicker/MGHorizontalPickerView.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymSlider/MG+Slider.swift
Labels: 리펙토링, 기능 추가

#186 auth usecase로 로직 빼기
  Projects/Data/Sources/Repository/IntroRepository.swift
  Projects/Domain/Project.swift
  Projects/Domain/Sources/Model/Auth/IntroModel.swift
  Projects/Domain/Sources/RepositoryInterface/IntroRepositoryInterface.swift
  Projects/Domain/Sources/UseCase/AuthUseCase.swift
  Projects/Features/AuthFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/AuthFeature/Sources/IntroScene/VC/IntroViewController.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/IntroViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/AgreeViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/CompleteSignUpViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/NicknameViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/AgreeViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/CompleteViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/NicknameViewModel.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymLabel /MG+Label.swift
  Projects/Modules/MGNetworks/Sources/Service/IntroService.swift
Labels: 도움, 훈수, 질문, 리펙토링

#189 :: [#187] 카카오 APi 연동
  Projects/Data/Sources/Repository/IntroRepository.swift
  Projects/Domain/Sources/RepositoryInterface/IntroRepositoryInterface.swift
  Projects/Domain/Sources/UseCase/AuthUseCase.swift
  Projects/Features/AuthFeature/Interface/Sources/AuthPresentable.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/IntroViewModel.swift
  Projects/Modules/MGNetworks/Sources/Foundation/Base/BaseAPI.swift
  Projects/Modules/MGNetworks/Sources/Service/IntroService.swift
Labels: 과제

#193 ⚓️:: [#188] 코드 복구
  Projects/Data/Sources/Repository/IntroRepository.swift
  Projects/Domain/Sources/RepositoryInterface/IntroRepositoryInterface.swift
  Projects/Domain/Sources/UseCase/AuthUseCase.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/IntroViewModel.swift
  Projects/Modules/MGNetworks/Sources/Service/IntroService.swift
Labels: 기능 추가

#195 :: [#190] 자세 - 추천 탭 - 리펙토링
  Projects/Data/Sources/Repository/PostureRepository.swift
  Projects/Domain/Sources/Model/Posture/Recommand/PostureRecommandModel.swift
  Projects/Domain/Sources/RepositoryInterface/PostureRepositoryInterface.swift
  Projects/Domain/Sources/UseCase/PostureUseCase.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Tab/PostureRecommandViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/ViewModel/Detail/PostureDetailViewModel.swift
  Projects/Features/PostureFeature/Sources/PostureScene/ViewModel/PostureMainViewModel.swift
  Projects/Features/PostureFeature/Sources/PostureScene/ViewModel/PostureSearchViewModel.swift
  Projects/Features/PostureFeature/Sources/PostureScene/ViewModel/Tab/PostureBackViewModel.swift
  Projects/Features/PostureFeature/Sources/PostureScene/ViewModel/Tab/PostureChestViewModel.swift
  Projects/Features/PostureFeature/Sources/PostureScene/ViewModel/Tab/PostureRecommandViewModel.swift
  Projects/Features/PostureFeature/Sources/PostureScene/ViewModel/Tab/PostureViewModel.swift
  Projects/Features/PostureFeature/Sources/Supporter/Recommand/PostureRecommandCollectionViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Recommand/PostureRecommandModel.swift
  Projects/Features/PostureFeature/Sources/Supporter/Recommand/PostureRecommandTableViewCell.swift
  Projects/Modules/MGNetworks/Sources/Service/PostureService.swift
Labels: 리펙토링

#199 :: [#198] 자세 - 디테일 - 리펙토링
  Projects/Data/Sources/Repository/PostureRepository.swift
  Projects/Domain/Sources/Model/Posture/PostureDetailModel.swift
  Projects/Domain/Sources/RepositoryInterface/PostureRepositoryInterface.swift
  Projects/Domain/Sources/UseCase/PostureUseCase.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Detail/PostureDetailViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/ViewModel/Detail/PostureDetailViewModel.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/Model/PostureDetailModel.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/RelatedPickle/PostureDetailPickeTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/RelatedPickle/PostureDetailPickleCollectionViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TitleImage/PostureDetailImageTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TitleInfo/PostureDetailExerciseInfoTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TitleTag/PostureDetailTagCollectionViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TitleTag/PostureDetailTagTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TitleText/PostureDetailTitleTableViewCell.swift
  Projects/Modules/MGNetworks/Sources/Service/PostureService.swift
Labels: 리펙토링

#201 194 메트로눔 - 소리에 맞추어 색바뀌는 작업
  Projects/Features/HomeFeature/Sources/MetronomeScene/Metronome.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/MetronomeViewController.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/MetronomeViewModel.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/View/NavigationBar/MetronomeNavigationBar.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/AddTimerView.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/HomeTimerView.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/MinGymKit/MinGaGymTimerKit.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/MinGymKit/MinGymKit.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerCollectionViewCell.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerModel.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerPickerView.swift
  Projects/Features/HomeFeature/Sources/TimerScene/View/TimerViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymSlider/MG+Slider.swift
Labels: 기능 추가

#205 카메라 UI 구현
  Projects/Features/SelfCareFeature/Sources/CameraScene/CameraViewController.swift
  Projects/Features/SelfCareFeature/Sources/CameraScene/View/NavigationBar/CameraNavigationBar.swift
  Projects/Features/SelfCareFeature/Sources/CameraScene/ViewModel/CameraViewModel.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/Camera/cameraButton.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Camera/cameraButton.imageset/Frame 735.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Camera/cameraButton.imageset/Frame 735@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Camera/cameraButton.imageset/Frame 735@3x.png
  Projects/Modules/MGCameraKit/Demo/Sources/Demo+/DemoViewController.swift
Labels: 기능 추가

#208 :: [#204] 자기관리 - 내 루틴 - 디테일
  Projects/Data/Sources/Repository/SelfCareRepository.swift
  Projects/Domain/Sources/Model/SelfCare/SelfCareMyRoutineDetailModel.swift
  Projects/Domain/Sources/RepositoryInterface/SelfCareRepositoryInterface.swift
  Projects/Domain/Sources/UseCase/SelfCareUseCase.swift
  Projects/Features/SelfCareFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareMyRoutineDetailViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareMyRoutineEditViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareMyRoutineViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/ViewModel/SelfCareMyRoutineDetail+VM.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Detail/MyRoutineDetailModel.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Detail/MyRoutineDetailTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Detail/MyRoutineDetailTitleView.swift
  Projects/Modules/MGNetworks/Sources/Service/SelfCareService.swift
Labels: 리펙토링, 기능 추가

#210 💉:: [#209] lint 수정
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareMyRoutineDetailViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareMyRoutineEditViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareMyRoutineViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/ViewModel/SelfCareMyRoutine+VM.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/ViewModel/SelfCareMyRoutineDetail+VM.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/ViewModel/SelfCareMyRoutineEdit+VM.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineCountView.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineCountViewType.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineEditModel.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineEditTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButton.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButtonType.swift
Labels: 리펙토링

#215 자기관리 메인 페이지 구현
  Projects/Domain/Sources/Model/SelfCare/Home/SelfCareIntroductModel.swift
  Projects/Domain/Sources/Model/SelfCare/Home/SelfCareMenuModel.swift
  Projects/Domain/Sources/Model/SelfCare/Home/SelfCareProfileModel.swift
  Projects/Features/HomeFeature/Demo/Sources/SceneDelegate.swift
  Projects/Features/SelfCareFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/SelfCareFeature/Sources/AlbumScene/AlbumViewController.swift
  Projects/Features/SelfCareFeature/Sources/AlbumScene/View/Cell/PhotoCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/SelfCareHomeViewController.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareIntroductTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareMenuCollectionCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareMenuTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareProfileTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/test.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/ViewModel/SelfCareHomeViewModel.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareFood.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareFood.imageset/SelfCareFood.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareFood.imageset/SelfCareFood@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareFood.imageset/SelfCareFood@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareGoul.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareGoul.imageset/SelfCareGoul.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareGoul.imageset/SelfCareGoul@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareGoul.imageset/SelfCareGoul@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareMainImage.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareMainImage.imageset/SelfCareMainImage.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareMainImage.imageset/SelfCareMainImage@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareMainImage.imageset/SelfCareMainImage@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareMenuMyRoutine.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareMenuMyRoutine.imageset/SelfCareMenuMyRoutine.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareMenuMyRoutine.imageset/SelfCareMenuMyRoutine@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareMenuMyRoutine.imageset/SelfCareMenuMyRoutine@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareOunwan.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareOunwan.imageset/SelfCareOunwan.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareOunwan.imageset/SelfCareOunwan@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/SelfCareOunwan.imageset/SelfCareOunwan@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/bage1.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/bage1.imageset/bage1.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/bage1.imageset/bage1@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/bage1.imageset/bage1@3x.png
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymProfile/MG+ProfileType.swift
Labels: 고치지 않음, 리펙토링, 기능 추가

#216 ⚓️ :: [#211] 자기관리 - 내 루틴 - 루틴 수정하기
  Projects/Data/Sources/Repository/SelfCareRepository.swift
  Projects/Domain/Sources/Model/SelfCare/SelfCareMyRoutineEditModel.swift
  Projects/Domain/Sources/RepositoryInterface/SelfCareRepositoryInterface.swift
  Projects/Domain/Sources/UseCase/SelfCareUseCase.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareMyRoutineEditViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/ViewModel/SelfCareMyRoutineEdit+VM.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Detail/MyRoutineDetailTitleView.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineCountView.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineCountViewType.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineEditModel.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineEditTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButtonType.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/selfCarePencil.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/selfCarePencil.imageset/selfCarePencil.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/selfCarePencil.imageset/selfCarePencil@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/SelfCareLogo/selfCarePencil.imageset/selfCarePencil@3x.png
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymTextField/MG+TitleTextField.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymVIew/MG+TitleTextView.swift
  Projects/Modules/MGNetworks/Sources/Service/SelfCareService.swift
Labels: 리펙토링, 기능 추가

#219 알럿 구현
  Projects/Core/Sources/Utils/UIControl+Utils.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/Alert/DSAlertViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/Button/DSToggleButtonVC.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/CaveatAlert/MGCaveatAlertViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/CaveatAlert/MGViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/DisappearedAlert/Icons/AlertIconDoneView.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/DisappearedAlert/Icons/AlertIconErrorView.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/DisappearedAlert/Icons/AlertIconHeartView.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/DisappearedAlert/Icons/AlertSpinnerView.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/DisappearedAlert/Supporter/AlertHaptic.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/DisappearedAlert/Supporter/AlertIcon.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/DisappearedAlert/Supporter/AlertKitAPI.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/DisappearedAlert/Supporter/AlertViewStyle.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/DisappearedAlert/Views/AlertViewInternalDismissProtocol.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/DisappearedAlert/Views/AlertViewProtocol.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/DisappearedAlert/Views/MG+AlertBarView.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/DisappearedAlert/Views/MG+AlertBoxView.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/DisappearedAlert/Views/MG+AlertOnlyTitleView.swift
Labels: 고치지 않음, 기능 추가

#221 💉:: [#220] 프로필 edit 뷰 추가
  Projects/Features/SelfCareFeature/Sources/HomeScene/SelfCareHomeViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/CaveatAlert/MGCaveatAlertViewController.swift
Labels: 고치지 않음

#222 :: [#217] 자기관리 - 목표 - 메인
  Projects/Data/Sources/Repository/SelfCareRepository.swift
  Projects/Domain/Sources/Model/SelfCare/Target/SelfCareTargetMainModel.swift
  Projects/Domain/Sources/RepositoryInterface/SelfCareRepositoryInterface.swift
  Projects/Domain/Sources/UseCase/SelfCareUseCase.swift
  Projects/Features/SelfCareFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/Target/SelfCareTargetMainViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/ViewModel/Target/SelfCareTargetMainViewModel.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/Target/Main/TargetMainTableViewCell.swift
  Projects/Modules/MGNetworks/Sources/Service/SelfCareService.swift
Labels: 기능 추가

#225 :: [#223] BaseButton 적용
  Projects/Core/Sources/Base/BaseButton.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/NicknameViewController.swift
  Projects/Features/HomeFeature/Sources/HomeScene/View/NavigationBar/HomeNavigationBar.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/MetronomeViewController.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/View/NavigationBar/MetronomeNavigationBar.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerAlarmAlertView.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/TimerEditView.swift
  Projects/Features/HomeFeature/Sources/TimerScene/View/TimerViewController.swift
  Projects/Features/SelfCareFeature/Sources/AlbumScene/View/NavigationBar/AlbumNavigationBar.swift
  Projects/Features/SelfCareFeature/Sources/CameraScene/CameraViewController.swift
  Projects/Features/SelfCareFeature/Sources/CameraScene/View/NavigationBar/CameraNavigationBar.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareMyRoutineDetailViewController.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineCountView.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineEditTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Main/MyRoutineTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/Target/Main/TargetMainTableViewCell.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/Alert/DSAlertViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/BottomSheet/DSBottomSheetViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/TextField/DSTextFieldViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/CaveatAlert/MGCaveatAlertViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Agree/MG+AgreeButton.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/MGButton/MaeumGaGymButton.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/MGImageButton/MaeumGaGymImageButton.swift
  Projects/Modules/MGCameraKit/Demo/Sources/Demo+/DemoViewController.swift
Labels: 리펙토링

#226 UILabel 제거 및 MGLabel 추가
  Projects/Core/Sources/Base/BaseLabel.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Extra/ExtraCollectionViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/MotivationMessage/MotivationMessageTableViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Routine/RoutineCollectionCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Routine/RoutineTableViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/StepNumber/StepTableViewCell.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/MetronomeViewController.swift
  Projects/Features/HomeFeature/Sources/TimerScene/Supporter/AddTimerView.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/UILabel/DSLabelVC.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/UILabel/DSPostureInfoLabelVC.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/UILabel/DSTagLabelVC.swift
  Projects/Modules/DSKit/Demo/Sources/DesignSystemDemo/ComponentsDemoTableViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DesignSystemDemo/TableView/Label/LabelTableView.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymLabel /MG+Label.swift
Labels: 고치지 않음, 리펙토링

#231 홈 이미지 리펙 중간 점검
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Extra/ExtraCollectionViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Extra/ExtraTableViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/MotivationMessage/MotivationMessageTableViewCell.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/MetronomeViewController.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/View/NavigationBar/MetronomeNavigationBar.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/HomeResourcesService.swift
Labels: 고치지 않음, 리펙토링

#233 홈 이미지 리펙 중간 점검
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Routine/RoutineTableViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/StepNumber/StepTableViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/View/NavigationBar/HomeNavigationBar.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/HomeResourcesService.swift
Labels: 고치지 않음, 리펙토링

#232 :: [#229] 이미지 리펙토링
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/basicProfileIcon.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/basicProfileIcon.imageset/basicProfile.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/basicProfileIcon.imageset/basicProfile@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/basicProfileIcon.imageset/basicProfile@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/cameraIcon.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/cameraIcon.imageset/camera.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/cameraIcon.imageset/camera@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/cameraIcon.imageset/camera@3x.png
Labels: 리펙토링

#235 홈 이미지 리펙 중간 점검
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Extra/ExtraCollectionViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Extra/ExtraTableViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Routine/RoutineCollectionCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/Routine/RoutineTableViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/StepNumber/StepTableViewCell.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/MetronomeViewController.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/HomeResourcesService.swift
Labels: 고치지 않음, 리펙토링

#237 🍗:: [#236] 피클 서비스 이미지
  Projects/Features/PickleFeature/Sources/PickleScene/VC/PickleCell.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Pickle/PickleLogoType.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/PickleResourcesService.swift
Labels: 리펙토링

#239 🍗:: [#238] 자기관리 리펙토링
  Projects/Features/SelfCareFeature/Sources/AlbumScene/AlbumViewController.swift
  Projects/Features/SelfCareFeature/Sources/AlbumScene/View/Cell/PhotoCell.swift
  Projects/Features/SelfCareFeature/Sources/AlbumScene/View/NavigationBar/AlbumNavigationBar.swift
  Projects/Features/SelfCareFeature/Sources/CameraScene/CameraViewController.swift
  Projects/Features/SelfCareFeature/Sources/CameraScene/View/NavigationBar/CameraNavigationBar.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/SelfCareHomeViewController.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareIntroductTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareMenuCollectionCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareMenuTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareProfileTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/test.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/SelfCareResourcesService.swift
Labels: 기능 추가

#241 Label 이름 변경했습니다.
  Projects/Features/PickleFeature/Sources/Supporter/Profile/UserProfileView.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/PostureMainViewController.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/RelatedPickle/PostureDetailPickeTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TitleCaution/PostureDetailCautionTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TitleInfo/PostureDetailExerciseInfoTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TitleText/PostureDetailTitleTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Search/PostureSearchTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Tab/PosturePartTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Tab/Recommand/PostureRecommandCollectionViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Tab/Recommand/PostureRecommandTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/AlbumScene/View/NavigationBar/AlbumNavigationBar.swift
  Projects/Features/SelfCareFeature/Sources/CameraScene/View/NavigationBar/CameraNavigationBar.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareIntroductTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareMenuCollectionCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareMenuTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareProfileTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareMyRoutineViewController.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/Target/SelfCareTargetMainViewController.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Detail/MyRoutineDetailTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButton.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/Target/Main/TargetMainTableViewCell.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/earthIcon.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/earthIcon.imageset/selfCareEarth.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/earthIcon.imageset/selfCareEarth@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/earthIcon.imageset/selfCareEarth@3x.png
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymBottonSheet/Supporter/MG+BottomSheetIconCell.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymBottonSheet/Supporter/MG+ShareCell.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Agree/MG+AgreeButton.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Auth/MG+AuthButton.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Check/MG+CheckButton.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Pickle/MG+OpaqueIconButton.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/SeeMore/MG+SeeMoreButton.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Timer/TimerButtonType.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Toggle/MG+ToggleButton.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymEmptyView/StatusLayoutView.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymProfile/MG+ProfileType.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymProfile/MG+ProfileView.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymVIew/MG+SearchView.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymVIew/MG+shareStateView.swift
Labels: 리펙토링

#243 코드 분리 및 이름 변경 완료 했습니다.
  Projects/Core/Sources/Base/BaseButton.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/Alert/DSCaveatAlertViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/Alert/DSDisappearAlertViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/BottomSheet/DSBottomSheetViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/Button/DSCameraButtonVC.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/HorizontalPicker/DSHorizontalPickerViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/TextField/DSTextFieldViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DesignSystemDemo/ComponentsDemoTableViewController.swift
  Projects/Modules/DSKit/Demo/Sources/DesignSystemDemo/TableView/Alert/AlertTableViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Agree/MG+AgreeButton.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/MGButton/MaeumGaGymButton.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymVIew/MG+SearchView.swift
  Projects/Modules/MGLogger/Sources/Level.swift
  Projects/Modules/MGLogger/Tests/Sources/UnitTest.swift
  Projects/Modules/TokenManager/Sources/KeychainType.swift
  Projects/Modules/TokenManager/Tests/Sources/UnitTest.swift
Labels: 리펙토링, 기능 추가

#247 :: [#246] 파일 구조 변경
  Projects/Features/PostureFeature/Sources/Supporter/Detail/CollectionViewCell/PostureDetailPickleCollectionViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/CollectionViewCell/PostureDetailTagCollectionViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TableViewCell/PostureDetailCautionTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TableViewCell/PostureDetailExerciseInfoTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TableViewCell/PostureDetailImageTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TableViewCell/PostureDetailPickeTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TableViewCell/PostureDetailTagTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TableViewCell/PostureDetailTitleTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Tab/Part/PosturePartTableViewCell.swift
Labels: 리펙토링

#250 :: [#248] 자세 - 전체 - 리펙토링
  Projects/Domain/Sources/Model/Posture/PostureDetailModel.swift
  Projects/Features/PostureFeature/Demo/Sources/SceneDelegate.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Detail/PostureDetailViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/PostureMainViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Tab/PostureBackViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Tab/PostureChestViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Tab/PostureRecommandViewController.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/CollectionViewCell/PostureDetailPickleCollectionViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/CollectionViewCell/PostureDetailTagCollectionViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/CollectionViewCell/PostureDetailTextCollectionViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TableViewCell/PostureDetailCautionTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TableViewCell/PostureDetailExerciseInfoTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TableViewCell/PostureDetailImageTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TableViewCell/PostureDetailInfoTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TableViewCell/PostureDetailPickeTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TableViewCell/PostureDetailTagTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/TableViewCell/PostureDetailTitleTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Search/PostureSearchTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Tab/Part/PosturePartTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Tab/Recommand/PostureRecommandCollectionViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Tab/Recommand/PostureRecommandTableViewCell.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymLabel /MG+Label.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymLabel /MG+PostureInfoLabel.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymLabel /MG+TagLabel.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/PostureDetailTextViewCollectionViewCell.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/PostureResourcesService.swift
  Projects/Modules/MGNetworks/Sources/Service/IntroService.swift
  Projects/Modules/MGNetworks/Sources/Service/PostureService.swift
Labels: 리펙토링

#252 사용자 프로필 만들었습니다.
  Projects/Features/SelfCareFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/SelfCareHomeViewController.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareProfileTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/ProfileScene/ProfileViewController.swift
  Projects/Features/SelfCareFeature/Sources/ProfileScene/View/BageView/SelfCareBageView.swift
  Projects/Features/SelfCareFeature/Sources/ProfileScene/View/NavigationBar/SelfCareProfileNavigationBar.swift
  Projects/Features/SelfCareFeature/Sources/ProfileScene/ViewModel/ProfileEditViewModel.swift
  Projects/Features/SelfCareFeature/Sources/SelfCareScene/View/SelfCareMyRoutineDetailViewController.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Detail/MyRoutineDetailTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineCountView.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Edit/MyRoutineEditTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/MyRoutine/Main/MyRoutineTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButtonType.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/Target/Main/TargetMainTableViewCell.swift
  Projects/Modules/DSKit/Demo/Sources/Application/SceneDelegate.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymProfile/MG+ProfileType.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/PostureResourcesService.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/SelfCareResourcesService.swift
  Projects/Modules/MGNetworks/Sources/Service/IntroService.swift
Labels: 기능 추가

#253 :: [#251] 자세 - 전체 리펙토링
  Projects/Data/Sources/Repository/PostureRepository.swift
  Projects/Domain/Sources/Model/Posture/PostureSearchModel.swift
  Projects/Domain/Sources/RepositoryInterface/PostureRepositoryInterface.swift
  Projects/Domain/Sources/UseCase/PostureUseCase.swift
  Projects/Features/PostureFeature/Demo/Sources/SceneDelegate.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Detail/PostureDetailViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Search/PostureSearchViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Tab/PostureBackViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/ViewModel/PostureSearchViewModel.swift
  Projects/Features/PostureFeature/Sources/Supporter/Search/PostureSearchModel.swift
  Projects/Features/PostureFeature/Sources/Supporter/Search/PostureSearchTableViewCell.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymTextField/MG+SearchTextField.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymVIew/MG+SearchView.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/PostureDetailTextViewCollectionViewCell.swift
  Projects/Modules/MGNetworks/Sources/Service/PostureService.swift
Labels: 리펙토링

#257 :: [#256] MG+TitleTextFieldView
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymTextField/MG+TitleTextField.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymTextField/TitleTextFieldType.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymVIew/MG+TitleTextFieldView.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymVIew/MG+TitleTextView.swift
Labels: 리펙토링

#260 🍗 :: [#259] 자세 - lint 에러 수정
  Projects/Features/PostureFeature/Sources/PostureScene/View/Detail/PostureDetailViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Search/PostureSearchViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Tab/PostureBackViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Tab/PostureChestViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Tab/PostureRecommandViewController.swift
Labels: 리펙토링

#262 :: [#261] 자기관리 - 서비스 구현
  Projects/Data/Sources/Repository/SelfCareRepository.swift
  Projects/Domain/Sources/Model/SelfCare/Target/SelfCareTargetDetailModel.swift
  Projects/Domain/Sources/RepositoryInterface/SelfCareRepositoryInterface.swift
  Projects/Domain/Sources/UseCase/SelfCareUseCase.swift
  Projects/Modules/MGNetworks/Sources/Service/SelfCareService.swift
Labels: 리펙토링
