Repository MaeumGaGym/MaeumGaGym_iOS, pull requests merged in 2024-07, with the labels that each got.

#358 REFACT :: [#346] home - 리펙토링
  Projects/Features/HomeFeature/Sources/HomeScene/View/NavigationBar/HomeNavigationBar.swift
  Projects/Features/HomeFeature/Sources/HomeScene/ViewController/HomeViewController.swift
  Projects/MaeumGaGym-iOS/Sources/Application/SceneDelegate.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymPagingTabBar/MG+PagingTabBar.swift
Labels: kind/리펙토링

#360 ADD :: [#359] 작업 방식 예시 추가
  Projects/Domain/Sources/UseCase/HomeUseCase.swift
  Projects/Domain/Sources/UseCase/PostureUseCase.swift
  Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/HomeViewModel.swift
Labels: kind/리펙토링

#363 FEAT :: 자기관리 정리 커밋
  Projects/Core/Sources/Coordinator/Setp/AppStep.swift
  Projects/Core/Sources/Coordinator/Stepper/Data/Tests/Sources/UnitTest.swift
  Projects/Features/HomeFeature/Sources/HomeScene/ViewModel/HomeViewModel.swift
  Projects/Features/SelfCareFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/VC/SelfCareHomeViewController.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareMenuTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/ViewModel/SelfCareHomeViewModel.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/VC/SelfCareMyRoutineAddViewController.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/VC/SelfCareMyRoutineDetailViewController.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/VC/SelfCareMyRoutineViewController.swift
  Projects/Features/SelfCareFeature/Sources/RoutineScene/View/Alert/MGSelfCareRoutineBottomSheet.swift
  Projects/Modules/MGFlow/Sources/Flow/HomeFlow.swift
  Projects/Modules/MGFlow/Sources/Flow/SelfCareFlow.swift
  Projects/Modules/MGNetworks/Sources/API/SelfCare/RoutineAPI.swift
  Projects/Modules/MGNetworks/Sources/Service/SelfCareService.swift
Labels: kind/리펙토링, kind/기능

#368 REFACT :: [#365] 화면 전환 에러 수정
  Projects/Features/PostureFeature/Sources/PostureScene/View/Search/PostureSearchViewController.swift
Labels: 버그 고치기

#370 FEAT :: [#369] 자기관리 - 프로필 기능 구현
  Projects/Core/Sources/Coordinator/Setp/AppStep.swift
  Projects/Core/Sources/Utils/UIControl+Utils.swift
  Projects/Core/Sources/Utils/UILabel+ChangeColor.swift
  Projects/Data/Sources/Repository/SelfCareRepository.swift
  Projects/Domain/Sources/Model/SelfCare/Profile/SelfCareProfileInfoModel.swift
  Projects/Domain/Sources/RepositoryInterface/SelfCareRepositoryInterface.swift
  Projects/Domain/Sources/Response/SelfCare/Profile/SelfCareProfileDTO.swift
  Projects/Domain/Sources/UseCase/AuthUseCase.swift
  Projects/Domain/Sources/UseCase/SelfCareUseCase.swift
  Projects/Features/AuthFeature/Sources/IntroScene/VC/SplashViewController.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/SplashViewModel.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Detail/PostureDetailViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/PostureMainViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Search/PostureSearchViewController.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/VC/SelfCareHomeViewController.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/View/Cell/SelfCareProfileTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/ViewModel/SelfCareHomeViewModel.swift
  Projects/Features/SelfCareFeature/Sources/ProfileScene/VC/ProfileEditViewController.swift
  Projects/Features/SelfCareFeature/Sources/ProfileScene/VC/ProfileViewController.swift
  Projects/Features/SelfCareFeature/Sources/ProfileScene/View/BageView/SelfCareBageView.swift
  Projects/Features/SelfCareFeature/Sources/ProfileScene/ViewModel/ProfileEditViewModel.swift
  Projects/Features/SelfCareFeature/Sources/ProfileScene/ViewModel/ProfileViewModel.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/CaveatAlert/MGCaveatAlertViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/CaveatAlert/MGViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymLabel /MG+Label.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymProfile/MG+ProfileView.swift
  Projects/Modules/MGFlow/Sources/Flow/AuthFlow.swift
  Projects/Modules/MGFlow/Sources/Flow/SelfCareFlow.swift
  Projects/Modules/MGNetworks/Sources/API/SelfCare/ProfileAPI.swift
  Projects/Modules/MGNetworks/Sources/Service/SelfCareService.swift
Labels: kind/리펙토링, kind/기능
