Repository MaeumGaGym/MaeumGaGym_iOS, pull requests merged in 2024-06, with the labels that each got.

#335 FEAT :: [#332] 자기관리 목표 뷰 퍼블리싱
  Plugins/EnvPlugin/ProjectDescriptionHelpers/Environment.swift
  Projects/Features/SelfCareFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/SelfCareFeature/Sources/HomeScene/VC/SelfCareHomeViewController.swift
  Projects/Features/SelfCareFeature/Sources/ProfileScene/View/NavigationBar/SelfCareProfileNavigationBar.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButton.swift
  Projects/Features/SelfCareFeature/Sources/Supporter/SelfCareButtonType.swift
  Projects/Features/SelfCareFeature/Sources/TargetScene/VC/SelfCareAddTargetViewController.swift
  Projects/Features/SelfCareFeature/Sources/TargetScene/VC/SelfCareDetailTargetViewController.swift
  Projects/Features/SelfCareFeature/Sources/TargetScene/VC/SelfCareTargetMainViewController.swift
  Projects/Features/SelfCareFeature/Sources/TargetScene/View/Alert/MGSelfCareTargetBottomSheetAlertView.swift
  Projects/Features/SelfCareFeature/Sources/TargetScene/View/Alert/MGTargetAlertView.swift
  Projects/Features/SelfCareFeature/Sources/TargetScene/View/Cell/TargetMainTableViewCell.swift
  Projects/Features/SelfCareFeature/Sources/TargetScene/View/MGDateSelectView.swift
  Projects/Features/SelfCareFeature/Sources/TargetScene/View/MGSelfCareTargetDateBannerView.swift
  Projects/Features/SelfCareFeature/Sources/TargetScene/ViewModel/SelfCareAddTargetViewModel.swift
  Projects/Features/SelfCareFeature/Sources/TargetScene/ViewModel/SelfCareDetailTargetViewModel.swift
  Projects/Features/SelfCareFeature/Sources/TargetScene/ViewModel/SelfCareTargetMainViewModel.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymTextField/MGSelfCareTextField.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymTextView/MgTextView.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: kind/기능

#337 REFACT :: [#334] 자세 - 디테일 리펙토링
  Projects/Domain/Sources/Model/Posture/PostureDetailModel.swift
  Projects/Features/PostureFeature/Demo/Sources/SceneDelegate.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Detail/PostureDetailViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/ViewModel/Detail/PostureDetailViewModel.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/PostureDetailTableViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Detail/PostureDetailTextCollectionViewCell.swift
  Projects/Modules/MGNetworks/Sources/Service/PostureService.swift
Labels: kind/리펙토링, kind/기능

#339 REFACT :: [#338] 자세 - Flow RF
  Projects/Features/PostureFeature/Demo/Sources/SceneDelegate.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/PostureMainViewController.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/recommandChestIcon.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/recommandChestIcon.imageset/recommandChestIcon.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/recommandChestIcon.imageset/recommandChestIcon@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/recommandChestIcon.imageset/recommandChestIcon@3x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/recommandShoulderIcon.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/recommandShoulderIcon.imageset/recommandShoulderIcon.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/recommandShoulderIcon.imageset/recommandShoulderIcon@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/recommandShoulderIcon.imageset/recommandShoulderIcon@3x.png
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymPagingTabBar/MG+PagingTabBar.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymPagingTabBar/MG+PagingTabBarCell.swift
  Projects/Modules/MGNetworks/Sources/Service/PostureService.swift
Labels: kind/리펙토링

#341 FEAT :: [#340] 자세 API 기반 구축
  Projects/Domain/Sources/Model/Posture/PostureDetailModel.swift
  Projects/Domain/Sources/Response/PoseDTO.swift
Labels: kind/기능

#345 REFACT :: [#344] auth 리펙토링
  Projects/Core/Sources/Utils/UIImage+Utils.swift
  Projects/Data/Sources/Repository/PostureRepository.swift
  Projects/Domain/Sources/Model/Posture/PostureRecommandModel.swift
  Projects/Domain/Sources/RepositoryInterface/PostureRepositoryInterface.swift
  Projects/Domain/Sources/Response/PoseDTO.swift
  Projects/Domain/Sources/UseCase/AuthUseCase.swift
  Projects/Domain/Sources/UseCase/PostureUseCase.swift
  Projects/Features/AuthFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/AuthFeature/Sources/IntroScene/VC/SplashViewController.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/SplashViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/Supporter/AuthSeemoreButton.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/AgreeViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/CompleteSignUpViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/NicknameViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/AgreeViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/CompleteViewModel.swift
  Projects/Features/HomeFeature/Demo/Sources/SceneDelegate.swift
  Projects/Features/HomeFeature/Sources/TimerScene/View/TimerViewController.swift
  Projects/Features/PickleFeature/Sources/PickleScene/VC/PicklePreparingViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/View/Tab/PostureRecommandViewController.swift
  Projects/Features/PostureFeature/Sources/PostureScene/ViewModel/Tab/PostureRecommandViewModel.swift
  Projects/Features/PostureFeature/Sources/Supporter/Tab/Recommand/PostureRecommandCollectionViewCell.swift
  Projects/Features/PostureFeature/Sources/Supporter/Tab/Recommand/PostureRecommandTableViewCell.swift
  Projects/MaeumGaGym-iOS/Sources/Application/SceneDelegate.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Check/MG+CheckButton.swift
  Projects/Modules/MGFlow/Sources/Flow/AuthFlow.swift
  Projects/Modules/MGFlow/Sources/Flow/HomeFlow.swift
  Projects/Modules/MGFlow/Sources/Flow/PickleFlow.swift
  Projects/Modules/MGNetworks/Sources/Service/AuthService.swift
  Projects/Modules/MGNetworks/Sources/Service/PostureService.swift
Labels: kind/리펙토링

#349 base 파일 주석 변경
  Projects/Core/Sources/Base/BaseButton.swift
  Projects/Core/Sources/Base/BaseLabel.swift
  Projects/Core/Sources/Base/BaseView.swift
  Projects/Core/Sources/Base/BaseViewController.swift
Labels: kind/문서

#351 auth - 리펙토링
  Projects/Features/AuthFeature/Demo/Sources/Application/AppDelegate.swift
  Projects/Features/AuthFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/AuthFeature/Interface/Sources/AuthPresentable.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/IntroViewModel.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/SplashViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/Supporter/AuthSeemoreButton.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/AgreeViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/NicknameViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/AgreeViewModel.swift
Labels: kind/리펙토링

#352 auth - 리펙토링
  .gitignore
Labels: kind/리펙토링

#354 Empty Preparing 추가
  Projects/Features/PickleFeature/Sources/PickleScene/VC/PicklePreparingViewController.swift
  Projects/Features/ShopFeature/Sources/ShopScene/View/ShopViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymPreparing/MGPreparingType.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymPreparing/MGPreparingViewController.swift
  Projects/Modules/MGFlow/Sources/Flow/PickleFlow.swift
  Projects/Modules/MGFlow/Sources/Flow/ShopFlow.swift
Labels: kind/리펙토링

#357 명언 뷰 구현
  Projects/Data/Sources/Repository/AuthRepository.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/MotivationMessage/MotivationMessageTableViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/StepNumber/StepTableViewCell.swift
Labels: kind/리펙토링
