Repository MaeumGaGym/MaeumGaGym_iOS, pull requests merged in 2024-03, with the labels that each got.

#267 test 작성
  Projects/Core/Sources/Utils/Array+Utils.swift
  Projects/Core/Sources/Utils/UIImage+Utils.swift
  Projects/Core/Tests/Sources/UnitTest.swift
  Projects/Core/Tests/Sources/Utils/MGImageExtensionTests.swift
  Projects/Core/Tests/Sources/Utils/MGStackViewExtensionTests.swift
  Projects/Core/Tests/Sources/Utils/MGUIViewExtesnsionTests.swift
  Projects/Modules/MGCameraKit/Tests/Sources/MGCameraUnitTest.swift
  Projects/Modules/MGNetworks/Sources/Foundation/Base/APIType.swift
  Projects/Modules/MGNetworks/Tests/Sources/IntroServiceTests.swift
  Projects/Modules/TestCore/Sources/UserDefaultKeyList+Test.swift
  Projects/Modules/TestCore/Sources/XCUIApplication+XCUIElements.swift
  Projects/Modules/TestCore/Sources/XCUIElement+.swift
Labels: 테스트 코드

#274 Test 자동화 모듈 추가
  .github/workflows/SwiftLint.yml
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Features/AuthFeature/Tests/Sources/UnitTest.swift
  Projects/Features/HomeFeature/Tests/Sources/HomeUnitTests.swift
  Projects/Features/HomeFeature/Tests/Sources/UnitTest.swift
  Projects/Features/HomeFeature/Tests/Sources/__Snapshots__/HomeUnitTests/test_홈_사진_스크린샷_저장.1.png
  Projects/Modules/TestCore/Project.swift
  Projects/Modules/TestCore/Sources/RxTestCase.swift
  Tuist/Dependencies.swift
Labels: 문서화, 리펙토링, 기능 추가

#275 :: [#IOS-5] 의존성 변경
  Projects/Demo/Project.swift
  Projects/Modules/MGFlow/Sources/Flow/PostureFlow.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: 버그 고치기

#276 걸음 데이터 받아오는 로직 구현
  Plugins/ConfigPlugin/Plugin.swift
  Plugins/ConfigPlugin/ProjectDescriptionHelpers/Configurations.swift
  Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlists.swift
  Projects/Core/Sources/Base/BaseViewController.swift
  Projects/Data/Sources/Repository/HomeRepository.swift
  Projects/Data/Sources/Repository/IntroRepository.swift
  Projects/Domain/Sources/Model/Home/StepModel.swift
  Projects/Features/HomeFeature/Demo/Sources/SceneDelegate.swift
  Projects/Features/HomeFeature/Sources/HealthKitStorage.swift
  Projects/Features/HomeFeature/Sources/HomeScene/TableViewCell/StepNumber/StepTableViewCell.swift
  Projects/Features/HomeFeature/Sources/HomeScene/ViewController/HomeViewController.swift
  Projects/Features/HomeFeature/Sources/MetronomeScene/MetronomeViewController.swift
  Projects/Features/HomeFeature/Tests/Sources/HomeUnitTests.swift
  Projects/Features/RootFeature/Demo/Sources/SceneDelegate.swift
  Projects/Modules/MGNetworks/Sources/Service/HomeService.swift
  Projects/Modules/ThirdPartyLibs/Project.swift
  Supporting/마음가짐.entitlements
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ProjectDescriptionHelpers/Settings.swift
  Workspace.swift
Labels: 기능 추가

#278 :: [#IOS-17] Auth - Flow
  Projects/Core/Sources/Coordinator/Setp/AppStep.swift
  Projects/Core/Sources/Coordinator/Stepper/AuthStepper.swift
  Projects/Features/AuthFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/AgreeViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/CompleteSignUpViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/NicknameViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/AgreeViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/NicknameViewModel.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymVIew/MG+AgreeView.swift
  Projects/Modules/MGFlow/Sources/Flow/AuthFlow.swift
Labels: 기능 추가

#279 :: [#IOS-20] Auth - MVVM
  Projects/Core/Sources/Coordinator/Stepper/AuthStepper.swift
  Projects/Data/Sources/Repository/AuthRepository.swift
  Projects/Domain/Sources/RepositoryInterface/AuthRepositoryInterface.swift
  Projects/Domain/Sources/UseCase/AuthUseCase.swift
  Projects/Features/AuthFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/AuthFeature/Sources/IntroScene/VC/IntroViewController.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/IntroViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/AgreeViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/AuthNavigationBarBar.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/NicknameViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/AgreeViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/CompleteViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/NicknameViewModel.swift
  Projects/Modules/MGFlow/Sources/Flow/AuthFlow.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/AuthResourcesService.swift
  Projects/Modules/MGNetworks/Sources/Service/AuthService.swift
Labels: 리펙토링, 기능 추가

#281 🥚:: [#IOS-29] goolge erorr
  .package.resolved
  .tuist-version
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Features/AuthFeature/Sources/IntroScene/VC/IntroViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/AgreeViewModel.swift
  Projects/MaeumGaGym-iOS/Project.swift
  Projects/Modules/MGFlow/Project.swift
  Projects/Modules/MGNetworks/Sources/Service/AuthService.swift
  Projects/Modules/ThirdPartyLibs/Project.swift
  Tuist/Dependencies.swift
  asdfasdf.jpeg
Labels: 고치지 않음

#282 Feat:: [#IOS-41] 템플릿 추가
  .github/ISSUE_TEMPLATE/test.yml
Labels: 기능 추가

#283 Settings for CICD Bot
  .github/pull_request_template.md
  OWNERS
Labels: kind/리펙토링, size/M

#287 Fix :: [IOS-44] moya 버그 수정 완료
  Plugins/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Modules/ThirdPartyLibs/Project.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: kind/버그, lgtm, size/XS

#288 target 권한 부여 및 코드 정리
  Supporting/WidgetExtension.entitlements
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  asdfasdf.jpeg
Labels: 버그 고치기, kind/리펙토링, lgtm, size/S

#289 FIX :: [#IOS-49] entitlements demo로 분리
  Supporting/마음가짐Demo.entitlements
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: kind/버그, 버그 고치기, lgtm, size/S

#290 AuthService
  Projects/Core/Sources/Base/BaseViewController.swift
  Projects/Data/Sources/Repository/AuthRepository.swift
  Projects/Domain/Sources/RepositoryInterface/AuthRepositoryInterface.swift
  Projects/Domain/Sources/Response/LoginDTO.swift
  Projects/Domain/Sources/Response/dummy4.swift
  Projects/Domain/Sources/UseCase/AuthUseCase.swift
  Projects/Features/AuthFeature/Sources/IntroScene/VC/IntroViewController.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/IntroViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/AgreeViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/NicknameViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/AgreeViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/NicknameViewModel.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/IntroIcon.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/IntroIcon.imageset/IntroIcon.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/IntroIcon.imageset/IntroIcon@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Icons/IntroIcon.imageset/IntroIcon@3x.png
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Agree/AgreeButtonType.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Agree/MG+AgreeButton.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymLabel /MG+Label.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymProfile/MG+ProfileType.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymTextField/MG+TextField.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymVIew/MG+AgreeView.swift
  Projects/Modules/MGNetworks/Sources/API/Auth/AppleAPI.swift
  Projects/Modules/MGNetworks/Sources/API/Auth/AuthAPI.swift
  Projects/Modules/MGNetworks/Sources/API/Auth/CsrfAPI.swift
  Projects/Modules/MGNetworks/Sources/API/Auth/GoogleAPI.swift
  Projects/Modules/MGNetworks/Sources/API/Auth/KakaoAPI.swift
  Projects/Modules/MGNetworks/Sources/Foundation/Base/APIType.swift
  Projects/Modules/MGNetworks/Sources/Foundation/Base/BaseAPI.swift
  Projects/Modules/MGNetworks/Sources/ResourcesService/AuthResourcesService.swift
  Projects/Modules/MGNetworks/Sources/Service/AuthService.swift
  Projects/Modules/TokenManager/Sources/KeychainType.swift
Labels: size/L

#292 :: 자기관리 - 서버 연동
  Projects/Modules/MGNetworks/Sources/API/SelfCare/RoutineAPI.swift
  Projects/Modules/MGNetworks/Sources/API/SelfCare/TargetAPI.swift
  Projects/Modules/MGNetworks/Sources/Foundation/Base/APIType.swift
  Projects/Modules/MGNetworks/Sources/Foundation/Base/BaseAPI.swift
Labels: kind/리펙토링, kind/기능
