Repository MaeumGaGym/MaeumGaGym_iOS, pull requests merged in 2024-05, with the labels that each got.

#310 REFACT :: [#309] Apple Oauth 마무리
  Projects/Domain/Sources/Response/LoginDTO.swift
  Projects/Domain/Sources/UseCase/AuthUseCase.swift
  Projects/Features/AuthFeature/Sources/IntroScene/VC/IntroViewController.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/IntroViewModel.swift
  Projects/Features/AuthFeature/Sources/SignupScene/VC/NicknameViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/NicknameViewModel.swift
  Projects/Modules/MGFlow/Sources/Flow/AuthFlow.swift
  Projects/Modules/MGNetworks/Sources/API/Auth/AppleAPI.swift
  Projects/Modules/MGNetworks/Sources/API/Auth/AuthAPI.swift
  Projects/Modules/MGNetworks/Sources/Service/AuthService.swift
  Projects/Modules/TokenManager/Sources/KeychainType.swift
Labels: kind/리펙토링, size/L, approved

#313 REFACT :: [#311] kakao Oauth 리펙토링
  Plugins/EnvPlugin/ProjectDescriptionHelpers/InfoPlists.swift
  Projects/Domain/Sources/UseCase/AuthUseCase.swift
  Projects/Features/AuthFeature/Demo/Sources/Application/AppDelegate.swift
  Projects/Features/AuthFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Modules/MGNetworks/Sources/API/Auth/KakaoAPI.swift
  Projects/Modules/MGNetworks/Sources/Service/AuthService.swift
Labels: kind/리펙토링, size/L, approved

#315 :: [#314] 구글 준비중 alert
  Projects/Features/AuthFeature/Sources/IntroScene/VC/IntroViewController.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/IntroViewModel.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymButton/Auth/MG+AuthButton.swift
Labels: kind/기능, size/S, approved

#320 REFACT :: [#316] 약관동의 페이지
  Projects/Features/AuthFeature/Sources/SignupScene/VC/AgreeViewController.swift
  Projects/Features/AuthFeature/Sources/SignupScene/ViewModel/AgreeViewModel.swift
Labels: kind/리펙토링, size/M, approved

#321 FEAT :: [#318] 자기관리-프로필 수정 퍼블리싱
  Projects/Features/SelfCareFeature/Sources/ProfileScene/VC/ProfileEditViewController.swift
  Projects/Features/SelfCareFeature/Sources/ProfileScene/VC/ProfileViewController.swift
  Projects/Features/SelfCareFeature/Sources/ProfileScene/View/NavigationBar/SelfCareProfileNavigationBar.swift
  Projects/Modules/DSKit/Demo/Sources/DemoViewController/DropDown/DSDropDown.swift
  Projects/Modules/DSKit/Demo/Sources/DesignSystemDemo/ComponentsDemoTableViewController.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/Arrow/bottomArrow.imageset/Chevron_Left 1.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Arrow/bottomArrow.imageset/Chevron_Left 2.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Arrow/bottomArrow.imageset/Chevron_Left.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Arrow/bottomArrow.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Arrow/topArrow.imageset/Chevron_Left 1.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Arrow/topArrow.imageset/Chevron_Left 2.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Arrow/topArrow.imageset/Chevron_Left.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Arrow/topArrow.imageset/Contents.json
  Projects/Modules/DSKit/Sources/Components/MGTabBarType/MGTabBarType.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymAlert/CaveatAlert/MGViewController.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymDropDown/MGDropDown.swift
  Projects/Modules/DSKit/Sources/Components/MaeumGaGymTextField/MGSelfCareTextField.swift
Labels: kind/리펙토링, kind/기능, size/XL

#328 FEAT :: [#324] Splash 뷰 구현
  Projects/Core/Sources/Coordinator/Setp/AppStep.swift
  Projects/Core/Sources/Coordinator/Stepper/AuthStepper.swift
  Projects/Data/Sources/Repository/AuthRepository.swift
  Projects/Domain/Sources/RepositoryInterface/AuthRepositoryInterface.swift
  Projects/Domain/Sources/UseCase/AuthUseCase.swift
  Projects/Features/AuthFeature/Demo/Sources/Application/AppDelegate.swift
  Projects/Features/AuthFeature/Demo/Sources/Application/SceneDelegate.swift
  Projects/Features/AuthFeature/Sources/IntroScene/VC/SplashViewController.swift
  Projects/Features/AuthFeature/Sources/IntroScene/ViewModel/SplashViewModel.swift
  Projects/Modules/DSKit/Resources/Assets.xcassets/Logo/splashLogo.imageset/Contents.json
  Projects/Modules/DSKit/Resources/Assets.xcassets/Logo/splashLogo.imageset/splashLogo.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Logo/splashLogo.imageset/splashLogo@2x.png
  Projects/Modules/DSKit/Resources/Assets.xcassets/Logo/splashLogo.imageset/splashLogo@3x.png
  Projects/Modules/MGFlow/Sources/Flow/AuthFlow.swift
  Projects/Modules/MGNetworks/Sources/Service/AuthService.swift
Labels: kind/기능

#330 REFACT :: [#327] Assets Extension 생성
  Projects/Modules/DSKit/Sources/Extension/Color/UIColor+.swift
  Projects/Modules/DSKit/Sources/Extension/Font/UIFont+.swift
  Projects/Modules/DSKit/Sources/Extension/Image/UIImage+.swift
Labels: kind/리펙토링, kind/기능

#333 FEAT :: [#329] 자세 API 기반 구축
  Projects/Modules/MGNetworks/Sources/API/Pose/PostureAPI.swift
  Projects/Modules/MGNetworks/Sources/Entity/dummy2.swift
Labels: kind/기능
